apiVersion: v1
kind: Pod
metadata:
  name: demo-memory
spec:
  containers:
    - name: demo-memory
      image: polinux/s05-kubernetes/08-secrets/readme.mdtress
      resources:
        limits:
          memory: "200Mi"
        requests:
          memory: "100Mi"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "190M", "--vm-hang", "1"]